#!/usr/bin/env python
from datetime import datetime
import sys

content = open('hrs.csv').readlines()
target = open('hrs.csv', 'w+')
checking_in = True
updated = ""
if len(content) == 0:
    updated += 'date,in,out,total\n'

for line in content:
    larr = line.split(',')
    if len(larr) == 4:
        updated += line
    elif len(larr) == 3:
        checking_in = False
        new = line.replace('\n','')
        now = datetime.now()
        minute = now.minute
	if minute < 10:
            minute = '0' + str(minute)
	new += "{}:{},".format(now.hour, minute)
        inhour = int(larr[1].split(':')[0])
        inminute = int(larr[1].split(':')[1])
        diff = (now.hour - inhour)*60 - inminute + now.minute
        new += "{}\n".format(float(diff/60) + float((diff%60))/60.0)
        updated += new

if checking_in:
    new = ""
    now = datetime.now()
    date = now.date()
    new += str(date) + ","
    time = now.time
    minute = now.minute
    if minute < 10:
        minute = '0' + minute
    new += "{}:{},".format(now.hour, minute)
    updated += new
print updated
target.write(updated)
target.close()
